name: CatsBreed
description: "Prueba tecnica para desarrollador Flutter en Pragma."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.9
  mockito: ^5.4.4
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter_native_splash:
  color: "#6429cd"
  android: true
  ios: true
  web: false
  image: assets/images/cat_splash.png
  branding: assets/images/branding.png
  android_12:
    color: "#6429cd"
    image: assets/images/cat_splash.png
    branding: assets/images/branding.png


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/loaders/
    - assets/images/
