// Mocks generated by Mockito 5.4.5 from annotations
// in catsBreed/test/presentation/providers/providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:catsBreed/domain/entities/cat.dart' as _i6;
import 'package:catsBreed/domain/enums/error_messages.dart' as _i5;
import 'package:catsBreed/domain/repositories/cat_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatRepository extends _i1.Mock implements _i3.CatRepository {
  MockCatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ErrorMessages, List<_i6.Cat>>> getCats() =>
      (super.noSuchMethod(
            Invocation.method(#getCats, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.ErrorMessages, List<_i6.Cat>>>.value(
                  _FakeEither_0<_i5.ErrorMessages, List<_i6.Cat>>(
                    this,
                    Invocation.method(#getCats, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.ErrorMessages, List<_i6.Cat>>>);
}
